title: Aadesh Upadhyay
url: "https://aadeshupadhyay.github.io/folio/"
baseurl: "/folio"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://aadeshupadhyay.github.io/folio/"
footer_text: Copyright © 2025 Aadesh Upadhyay

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/folio/"
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "res.pdf"
 - name: "Contact"
   link: "contact"
